- alias: azam
  lab_member: True
  name: Azam Nasir (Azam)
  name_as_author: XXX
  role: CFO
  avatar: bio-azam.jpg
  email: azmudd@gmail.com
  twitter: GenomicsFast
  github: azamuddeen97
  linkedin: muhammad-azamuddeen-mohammad-nasir-436441190
  orcid: 0000-0001-9065-1795
  tiktok: azamuddeennasir
  address: Monash University Malaysia
  bio: "I am Azam. I have an affinity towards the natural sciences and love to be high up on the tree tops or deep in limestone caves to get up close in nature."
  affiliations:
    - title: PhD student
      inst: Monash University Malaysia
      inst_link: https://www.monash.edu.my/
      current: true

- alias: zarul
  lab_member: True
  name: Zarul Hanifah (Zarul)
  name_as_author: Muhammad Zarul Hanifah Md Zoqratt
  role: CEO
  github: ZarulHanifah
  avatar: bio-zarul.jpg
  email: zarulsaurus@gmail.com
  twitter: Zarul_Hanifah
  github: ZarulHanifah
  linkedin: zarul-hanifah-699412105
  orcid: 0000-0002-5075-1828
  phone: +601160905857 
  address: Monash University Malaysia
  bio: "I am Zarul. Servant to the microbiome. What's in your data? Give dat to me"
  affiliations:
    - title: PhD student
      inst: Monash University Malaysia
      inst_link: https://www.monash.edu.my/
      current: true

- alias: shania
  lab_member: True
  name: Shania Mira (Shania)
  avatar: bio-shania.jpg
  role: Intern
  email: shaniamira16@gmail.com
  address: Monash University Malaysia
  bio: "I am Shania, my interests gravitate towards the world of microbes and its implementation in our daily lives. I enjoy outdoor activities such as swimming and hiking."
  affiliations:
    - title: Undergraduate student
      inst: Monash University Malaysia

- alias: jason
  lab_member: True
  name: Sio Jia Shen (Jason)
  avatar: bio-jiashen.png
  role: Intern
  email: siojiashen111@gmail.com
  insta: Jiashen_sio
  linkedin: jia-shen-sio-9286a026b
  address: Monash University Malaysia
  bio: "Hello, I am Jia Shen. My passion is about unravelling the mysteries of life through genomics, driven by a deep curiosity to explore how genes shape health, evolution, and innovation."
  affiliations:
    - title: Bachelor degree Science student
      inst: Monash University Malaysia

- alias: julian
  lab_member: True
  name: Julian Ying (Julian)
  avatar: bio-julian.jpg
  role: Intern
  address: Monash University Malaysia
  bio: "Hello, I am Julian."
  affiliations:
    - title: Bachelor degree Science student
      inst: Monash University Malaysia

####################################################################################
# Lab Alumni.
####################################################################################

# - alias: sam
#   lab_member: True
#   name: Samuel Miller
#   name_as_author: Samuel E Miller
##  tenure_start: 11/2019
##  tenure_end: 9/2022
##  nick_name: Sam
##  contributions: "Sam took on one of the most exciting challenges our group has to offer: taking advantage of the recent advances in high-throughput sequencing of short RNA molecules to make sense of microbial tRNA transcripts in complex habitats. Towards this goal, he developed novel and advanced open-source software tools to study all aspects of chemical modification and relative abundance analysis of tRNA transcripts, and combining them with tRNA genes, codons, and metabolisms found in genomes and metagenomes"
##  current_info: a Scientific Programmer for <a href="https://ccomp-stc.org/" target="_blank">the Center for Chemical Currencies of a Microbial Planet</a> at the <a href="https://mbl.edu" target="_blank">Marine Biological Laboratory</a>.
#   role: Post-doctoral Scientist
#   email: samuelmiller@uchicago.edu
#   orcid: 0000-0002-2836-1401
#   twitter: smiller_science
#   github: semiller10
#   web: https://semiller10.github.io
#   avatar: bio-sam.jpg
#   address: Knapp Center for Biomedical Discovery, 900 E. 57th St., MB 9, RM 9148, Chicago, IL 60637 USA
#   bio: "I study how microbes function in their environments by developing and applying computational tools to interpret data from approaches such as tRNA-sequencing, proteomics, and metagenomics."
#   affiliations:
#     - title: Post-doctoral Scientist
#       inst: The Department of Medicine at the University of Chicago
#       inst_link: http://medicine.uchicago.edu/

- alias: harpreet
  lab_member: True
  name: Harpreet Kaur (Harpreet)
  role: COO
  name_as_author: Harpreet Kaur
  avatar: bio-harpreet.jpg
  tenure_start: the start
  tenure_end: sometime in 2023
  nick_name: Harpreet
  email: harpreet9595@gmail.com
  twitter: GenomicsFast 
  github: Harpreeeeet
  linkedin: harpreet-kaur-729b83107
  orcid: 0009-0003-1937-3835
  phone: +60173710644 
  address: Monash University Malaysia
  bio: "I am Harpreet. I love anything and everything related to microbiology. I can feel it in my gut. "
  affiliations:
    - title: PhD student
      inst: Monash University Malaysia
      inst_link: https://www.monash.edu.my/
      current: true

- alias: rainier
  name: Rainier William
  lab_member: True
  name_as_author: Rainier William
  avatar: bio-rainier.jpg
  role: Intern
  instagram: rainierwilliam
  email: rainierwilliam516@gmail.com
  tenure_start: the start
  tenure_end: sometime in 2023
  twitter: N/A
  github: N/A
  linkedin: Rainier William
  orcid: 0009-0001-7548-6821
  address: Monash University Malaysia
  bio: "I am Rainier and it was when I came across genomics that I fell in love with Biology."
  affiliations:
      - title: Bachelor of Science Student 


####################################################################################
# Collaborators and partners in science
####################################################################################

# - alias: mikeyu
#   collaborator: True
#   name: Michael Yu
#   name_as_author: Michael K Yu
#   avatar: bio-mikeyu.jpg
#   email: mikeyu@ttic.edu
#   web: https://www.ttic.edu/faculty/yu/
#   role: Partner in Science / Collaborator
#   linkedin: michaelyumit
#   github: michaelkyu
#   bio: "I develop new machine learning methods and algorithms to study large biomedical datasets. I'm interested in transferring techniques in computational biology to other fields, including natural language processing."
#   affiliations:
#     - title: Research Assistant Professor
#       inst: Toyota Technological Institute at Chicago
#       inst_link: https://www.ttic.edu/

####################################################################################
# Community Guests & Contributors
####################################################################################

# - alias: chiara
#   community_member: True
#   name: Chiara Vanni
#   name_as_author: Chiara Vanni
#   avatar: bio-chiara.jpg
#   email: cvanni@mpi-bremen.de
#   orcid: 0000-0002-1124-1147
#   github: ChiaraVanni
#   web: https://scholar.google.com/citations?user=0-KzK6MAAAAJ&hl=en
#   role: Contributing hero
#   twitter: ChiaraVanni5
#   affiliations:
#     - title: Graduate Student
#       inst: Max Planck Institute for Marine Microbiology
#       inst_link: https://mpi-bremen.de
